Release 1.3.42.0
ElrondNetwork/elrond-config-mainnet pull request #135
Opened 2022-06-30 15:10 UTC by andreibancioiu

- Release 1.3.42.0 (rc/2022-july).

2022-06-30 15:19 UTC, andreibancioiu commented on api.toml
> +        { Name = "/genesis-balances", Open = true }
This endpoint is brought by `feat/rosetta`.

2022-06-30 15:19 UTC, andreibancioiu commented on config.toml
> +    # TODO: Change this address.
We have to change this config.

2022-09-21 08:20 UTC, raduchis requested changes

2022-09-21 08:20 UTC, raduchis commented on config.toml
> +    HeartbeatExpiryTimespanInSec                     = 3600 # 1h
should be increased to more than PeerAuthenticationTimeBetweenSendsInSec.
Also please add the comment with greater than PeerAuthenticationTimeBetweenSendsInSec

2022-09-21 08:36 UTC, raduchis approved these changes

2022-09-26 13:37 UTC, iulianpascalau approved these changes

2022-09-26 13:37 UTC, merged