docker image
ElrondNetwork/elrond-config-mainnet pull request #42
Opened 2021-05-14 13:42 UTC by miiu96

2021-05-14 13:59 UTC, liviuancas-elrond approved these changes

2021-05-18 07:12 UTC, iulianpascalau requested changes

2021-05-18 07:12 UTC, iulianpascalau commented on scripts/run-observer.sh
> +        echo "node is syncing... nonce is growing"
...is increasing

2021-05-21 12:30 UTC, iulianpascalau approved these changes

2021-05-21 12:31 UTC, miiu96 commented on scripts/run-observer.sh
> +        echo "node is syncing... nonce is growing"
done.

2021-05-21 13:06 UTC, liviuancas-elrond approved these changes

2021-05-30 18:12 UTC, merged